### ISSUE TITLE
gfortran compiler (gfortran_win-64) unsatisfiable dependency for isce2

### ISSUE THREAD

**Issue by sgbaird** [piyushrpt/recipes-test#2]
```python
(mat_discover) PS C:\Users\sterg\Documents\GitHub\scratch\recipes-test\recipes\isce2> ls


    Directory: C:\Users\sterg\Documents\GitHub\scratch\recipes-test\recipes\isce2


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/21/2021   3:19 PM                scripts
-a----        10/21/2021   3:19 PM           1580 build.sh
-a----        10/21/2021   3:19 PM            846 meta.yaml
-a----        10/21/2021   3:19 PM           1390 README.md


(mat_discover) PS C:\Users\sterg\Documents\GitHub\scratch\recipes-test\recipes\isce2> conda build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for isce2
INFO:conda_build.metadata:Attempting to finalize metadata for isce2
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 C:\Users\sterg\miniconda3\conda-bld\work
  Test:
 C:\Users\sterg\miniconda3\conda-bld\test_tmp
Leaving build/test environments:
  Test:
source activate  C:\Users\sterg\miniconda3\conda-bld\_test_env
  Build:
source activate  C:\Users\sterg\miniconda3\conda-bld\_build_env


Traceback (most recent call last):
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\environ.py", line 802, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\core\solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\core\solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\core\solve.py", line 565, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\resolve.py", line 555, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\resolve.py", line 576, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda\resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - gfortran_win-64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sterg\miniconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\api.py", line 186, in build
    return build_tree(
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\build.py", line 2031, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\render.py", line 789, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\metadata.py", line 2115, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\metadata.py", line 776, in finalize_outputs_pass
    fm = finalize_metadata(om, parent_metadata=parent_metadata,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\render.py", line 547, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(m,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\render.py", line 387, in add_upstream_pins
    build_deps, build_unsat, extra_run_specs_from_build = _read_upstream_pin_files(m, 'build',
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\render.py", line 374, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\render.py", line 139, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "C:\Users\sterg\miniconda3\lib\site-packages\conda_build\environ.py", line 804, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'gfortran_win-64'}
```

**Comment by piyushrpt** [comment]
The more up to date recipes are here: https://github.com/conda-forge/isce2-feedstock . Not sure if this has ever been tested on windows
